### ISSUE TITLE
Sleeves causing high lag and has a white cube around it when equipped

### ISSUE THREAD

**Issue by Rocoro** [Silverfeelin/Starbound-OutfitGenerator#14]
When I put in the spawn sleeves command my whole computer starts lagging out thankfully for me it takes less then a minute to fix itself anyway back to topic when it finally spawns it spawns a white cube with the idle arm picture on it (it is the one I want I just dont want the white cube around it) I equip it and my framerate drops like a rocket flieing downwards the animations work except the animated arm is all I see the rest of the sprite is covered by a big white cube the low framerate only drops when it is equipped or being held

**Comment by Rocoro** [comment]
I think the reason my computer lags when I paste in the command is because its extremely big command

**Comment by Rocoro** [comment]
The rest of the clothes work fine tho

**Comment by Silverfeelin** [comment]
You're correct, Starbound has issues rendering large amounts  lof text.


Did you use the sleeve template? It's different from a normal sleeves sprite sheet.

Regarding memory/lag, see https://github.com/Silverfeelin/Starbound-OutfitGenerator/issues/1

**Comment by Rocoro** [comment]
I opened up the sleeves template with paint then I pasted the back and front arms onto it and moved them perfectly over the template pictures in the correct position

**Comment by Silverfeelin** [comment]
MS Paint doesn't support alpha values. You saved the image with a white background. Consider using software such as [Paint.NET](https://www.getpaint.net/) or [GIMP](https://www.gimp.org/).

When saving the image, I highly suggest saving to `.png` with a 32-bit depth, as illustrated below for Paint.NET.
![image](https://user-images.githubusercontent.com/17196309/50488525-40367080-0a03-11e9-808a-ca4da6f773c2.png)

**Comment by Rocoro** [comment]
okay thx

**Comment by Silverfeelin** [comment]
If you have any further issues with this please reply. Marking this issue as solved.
