### ISSUE TITLE
After 1.4.2 update there are some broken frames

### ISSUE THREAD

**Issue by NeonHawken** [Silverfeelin/Starbound-OutfitGenerator#16]
After a 1.4.2 update some frames of sleeves got currupted and look like this
![image](https://user-images.githubusercontent.com/52212658/60114813-41abe000-977d-11e9-998c-98f66237fb84.png)
It appears while holding a weapon and while falling (8 frame front hand).
May be it because of update?

**Comment by KrashV** [comment]
It's being looked into now.
We'll post the update as soon as possible

**Comment by Silverfeelin** [comment]
Resolved in https://github.com/Silverfeelin/Starbound-OutfitGenerator/commit/23c454300cf8ad3df11db58c01ce2487c8763712. Thank you.

Released in 1.4.2: https://github.com/Silverfeelin/Starbound-OutfitGenerator/releases
