### ISSUE TITLE
Sleeve Generator not working

### ISSUE THREAD

**Issue by CrowRider** [Silverfeelin/Starbound-OutfitGenerator#2]
I get this error thing on the console and it crashes for me.
http://imgur.com/a/rtlqz

**Comment by Silverfeelin** [comment]
Try the following:

* Unpack the files to an empty folder (not into the unpacked source code).
* Ensure you have .NET Framework 4.5 installed.

**Comment by CrowRider** [comment]
Turns out you need both files in the same folder for it to work.

**Comment by Silverfeelin** [comment]
Apologies for the late response. The README has been updated in commit https://github.com/Silverfeelin/Starbound-OutfitGenerator/commit/b01c1e9981bb5a82a934d4c500b23a4cb56954dc to make this clear.
