### ISSUE TITLE
Hatter

### ISSUE THREAD

**Issue by KrashV** [Silverfeelin/Starbound-OutfitGenerator#6]
Wouldn't it be great if we could add an option to generate custom hats here as well?
That would keep the Outfit generator together.

Probably no need to use NeetleBoy's method for now, due to limitations of it.
Or not: up to you!

**Comment by Silverfeelin** [comment]
I've (finally) started working on this in the branch [wip-Hat](https://github.com/Silverfeelin/Starbound-OutfitGenerator/tree/wip-Hat).  
I'm using a similar algorithm to the ones used by the other clothing pieces to conserve some data.

Still need to add an option to mask hair.

**Comment by Silverfeelin** [comment]
Added in https://github.com/Silverfeelin/Starbound-OutfitGenerator/commit/a94c46bd840eb8b96ae11a580e06089ba80793d1

Thanks for your contribution :)
